### ISSUE TITLE
Is this still being updated daily?

### ISSUE THREAD

**Issue by DrewDennison** [nice-registry/all-the-package-names#13]
Hello,

I love the idea of your package. It looks like it hasn't been running daily since May 25th according to the commit logs. Is this project still maintained?

**Comment by zeke** [comment]
I'm still here but I haven't been babysitting it lately. My guess is that it's not working now because npm, Inc deleted all tokens a while back due to a security incident they had.

I will make a note to look into updating the npm token and keep you posted.

**Comment by zeke** [comment]
Good morning, @DrewDennison.

Automated publishing is working again. Here's the latest version: https://www.npmjs.com/package/all-the-package-names

FYI, It was broken because the buildpacks used by the Heroku app were moved from my personal GitHub account to orgs:

- https://github.com/nice-registry/npm-buildpack
- https://github.com/github-modules/github-buildpack

For details on how this process works, see http://zeke.sikelianos.com/npm-and-github-automation-with-heroku/
