### ISSUE TITLE
This is going to be bigger and bigger

### ISSUE THREAD

**Issue by IonicaBizau** [nice-registry/all-the-package-names#3]
@zeke Is there any way to keep the size of the repo the same while time is passing on? This is already pretty big and it will be bigger and bigger.

**Comment by zeke** [comment]
I'm open to ideas..

**Comment by IonicaBizau** [comment]
@zeke Maybe run the extract script after installing (a `postinstall` script)?

**Comment by zeke** [comment]
>  run the extract script after installing

☝️ This is a good technique, and one I use elsewhere for things like [all-the-packages](https://github.com/zeke/all-the-packages/blob/f88cdf35194a711a42a0a46c282bfe07bc74a670/package.json#L7)

But this package is different. I want users to have access to a dependency-free list of package names that is "accurate enough". If we were to add a postinstall script, it would require a full streaming of the contents of the registry on every install, which would take a long time per user. The hourly re-releasing of the package takes that burden off the user and onto the publisher (a bot). 

I wrote about the technique I'm using to automate this at http://zeke.sikelianos.com/npm-and-github-automation-with-heroku/

Also, this module is kind of a :trollface: to illustrate the fact that there's no documented public API for the npm registry. There is an undocumented, [unmaintained](https://github.com/npm/npm-registry-couchapp/commit/417c3d82aa036ba66eddfc893f16a6727f2ecb4d), and [incomplete](https://github.com/npm/registry/issues/41#issuecomment-236342239) couch database. There is the [npm/public-api](https://github.com/npm/public-api/issues) repo, but it's been mostly quiet in the 18 months since its inception.

**Comment by IonicaBizau** [comment]
@zeke Makes sense! 

What if we set up the bot to override the commits so it won't keep all the world history in this git repo? Because in the end, that's the problem, that the git repo itself gets bigger. 😁

**Comment by wmhilton** [comment]
> Also, this module is kind of a :trollface: to illustrate the fact that there's no documented public API for the npm registry. There is an undocumented, unmaintained, and incomplete couch database. There is the npm/public-api repo, but it's been mostly quiet in the 18 months since its inception.

^so many feels

**Comment by zeke** [comment]
yes. many feels.

Here's my current work to share more consumable registry metadata:

https://github.com/zeke/dependent-packages
https://github.com/zeke/package-stream
https://github.com/zeke/nice-package
https://github.com/zeke/all-the-packages
https://github.com/zeke/electron-npm-packages

**Comment by wmhilton** [comment]
What ARE you building with all these tools? 🤨

**Comment by zeke** [comment]
Working toward an understanding of the most popular and useful userland tools for Electron. Hoping to display this data on Electron's website soon.

**Comment by zeke** [comment]
Yes this is getting bigger, but so far that hasn't been a problem. We can reopen this when and if the size becomes a problem.

**Comment by IonicaBizau** [comment]
I agree! 😁
